{"name": "Тест клика по кнопке \"Восстановить\" с введеной существующей почтой", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=124.0.6367.78)\nStacktrace:\n0   chromedriver                        0x00000001031c68dc chromedriver + 4368604\n1   chromedriver                        0x00000001031bed70 chromedriver + 4337008\n2   chromedriver                        0x0000000102de2c04 chromedriver + 289796\n3   chromedriver                        0x0000000102dbd918 chromedriver + 137496\n4   chromedriver                        0x0000000102e49ab8 chromedriver + 711352\n5   chromedriver                        0x0000000102e5cd08 chromedriver + 789768\n6   chromedriver                        0x0000000102e19ab4 chromedriver + 514740\n7   chromedriver                        0x0000000102e1a50c chromedriver + 517388\n8   chromedriver                        0x000000010318adf8 chromedriver + 4124152\n9   chromedriver                        0x000000010318fbe8 chromedriver + 4144104\n10  chromedriver                        0x00000001031707c0 chromedriver + 4016064\n11  chromedriver                        0x0000000103190518 chromedriver + 4146456\n12  chromedriver                        0x0000000103162274 chromedriver + 3957364\n13  chromedriver                        0x00000001031afe60 chromedriver + 4275808\n14  chromedriver                        0x00000001031affdc chromedriver + 4276188\n15  chromedriver                        0x00000001031be9d0 chromedriver + 4336080\n16  libsystem_pthread.dylib             0x000000018fe1d034 _pthread_start + 136\n17  libsystem_pthread.dylib             0x000000018fe17e3c thread_start + 8", "trace": "self = <tests.test_password_recoverty.TestsPasswordRecovery object at 0x102bcfa10>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1b43992cf3383d2efcdc1e46f975a9fb\")>\nuser = {'email': 'mqttkorcrt@gmail.com', 'json': {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmE... 'user': {'email': 'mqttkorcrt@gmail.com', 'name': 'vnistkzejs'}}, 'name': 'vnistkzejs', 'password': 'onlyiiywlz', ...}\n\n    @allure.title('Тест клика по кнопке \"Восстановить\" с введеной существующей почтой')\n    def test_enter_email_click_recovery(self, driver, user):\n        page = PasswordRecoveryPage(driver)\n        page.open(Url.FORGOT_PASSWORD_PAGE)\n        page.send_data_to_email_input(user['email'])\n        page.click_recovery_button()\n>       page.wait_url_change(Url.RESET_PASSWORD_PAGE)\n\ntests/test_password_recoverty.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/base_page.py:24: in wait_url_change\n    return WebDriverWait(self.driver, time).until(ec.url_to_be(url))\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:96: in until\n    value = method(self._driver)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py:125: in _predicate\n    return url == driver.current_url\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:437: in current_url\n    return self.execute(Command.GET_CURRENT_URL)[\"value\"]\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x102c076e0>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such window\",\"message\":\"no such window: target window already closed\\\\...00018fe1d034 _pthread_start + 136\\\\n17  libsystem_pthread.dylib             0x000000018fe17e3c thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nE       from unknown error: web view not found\nE         (Session info: chrome=124.0.6367.78)\nE       Stacktrace:\nE       0   chromedriver                        0x00000001031c68dc chromedriver + 4368604\nE       1   chromedriver                        0x00000001031bed70 chromedriver + 4337008\nE       2   chromedriver                        0x0000000102de2c04 chromedriver + 289796\nE       3   chromedriver                        0x0000000102dbd918 chromedriver + 137496\nE       4   chromedriver                        0x0000000102e49ab8 chromedriver + 711352\nE       5   chromedriver                        0x0000000102e5cd08 chromedriver + 789768\nE       6   chromedriver                        0x0000000102e19ab4 chromedriver + 514740\nE       7   chromedriver                        0x0000000102e1a50c chromedriver + 517388\nE       8   chromedriver                        0x000000010318adf8 chromedriver + 4124152\nE       9   chromedriver                        0x000000010318fbe8 chromedriver + 4144104\nE       10  chromedriver                        0x00000001031707c0 chromedriver + 4016064\nE       11  chromedriver                        0x0000000103190518 chromedriver + 4146456\nE       12  chromedriver                        0x0000000103162274 chromedriver + 3957364\nE       13  chromedriver                        0x00000001031afe60 chromedriver + 4275808\nE       14  chromedriver                        0x00000001031affdc chromedriver + 4276188\nE       15  chromedriver                        0x00000001031be9d0 chromedriver + 4336080\nE       16  libsystem_pthread.dylib             0x000000018fe1d034 _pthread_start + 136\nE       17  libsystem_pthread.dylib             0x000000018fe17e3c thread_start + 8\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchWindowException"}, "steps": [{"name": "Открываем браузер на заданом урле", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/forgot-password'"}], "start": 1714056691887, "stop": 1714056718907}, {"name": "Ввод данных в инпут \"Email\"", "status": "passed", "steps": [{"name": "Ожидаем элемент и вводим данные", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//input[@name=\"name\"]')"}, {"name": "data", "value": "'mqttkorcrt@gmail.com'"}, {"name": "time", "value": "15"}], "start": 1714056718908, "stop": 1714056719011}], "parameters": [{"name": "data", "value": "'mqttkorcrt@gmail.com'"}], "start": 1714056718908, "stop": 1714056719011}, {"name": "Клик по кнопке \"Восстановить\"", "status": "passed", "steps": [{"name": "Перемещаемся до элемента и кликаем", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//button[contains(text(),\"Восстановить\")]')"}], "start": 1714056719012, "stop": 1714056719298}], "start": 1714056719012, "stop": 1714056719298}, {"name": "Дожидаемся смены урла", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=124.0.6367.78)\nStacktrace:\n0   chromedriver                        0x00000001031c68dc chromedriver + 4368604\n1   chromedriver                        0x00000001031bed70 chromedriver + 4337008\n2   chromedriver                        0x0000000102de2c04 chromedriver + 289796\n3   chromedriver                        0x0000000102dbd918 chromedriver + 137496\n4   chromedriver                        0x0000000102e49ab8 chromedriver + 711352\n5   chromedriver                        0x0000000102e5cd08 chromedriver + 789768\n6   chromedriver                        0x0000000102e19ab4 chromedriver + 514740\n7   chromedriver                        0x0000000102e1a50c chromedriver + 517388\n8   chromedriver                        0x000000010318adf8 chromedriver + 4124152\n9   chromedriver                        0x000000010318fbe8 chromedriver + 4144104\n10  chromedriver                        0x00000001031707c0 chromedriver + 4016064\n11  chromedriver                        0x0000000103190518 chromedriver + 4146456\n12  chromedriver                        0x0000000103162274 chromedriver + 3957364\n13  chromedriver                        0x00000001031afe60 chromedriver + 4275808\n14  chromedriver                        0x00000001031affdc chromedriver + 4276188\n15  chromedriver                        0x00000001031be9d0 chromedriver + 4336080\n16  libsystem_pthread.dylib             0x000000018fe1d034 _pthread_start + 136\n17  libsystem_pthread.dylib             0x000000018fe17e3c thread_start + 8\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/olegandreev/Documents/yandexrepo/Diplom/Diplom_3/pages/base_page.py\", line 24, in wait_url_change\n    return WebDriverWait(self.driver, time).until(ec.url_to_be(url))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/support/expected_conditions.py\", line 125, in _predicate\n    return url == driver.current_url\n                  ^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 437, in current_url\n    return self.execute(Command.GET_CURRENT_URL)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/reset-password'"}, {"name": "time", "value": "15"}], "start": 1714056719298, "stop": 1714056726084}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1714056691887, "stop": 1714056726091, "uuid": "dba23e6f-098a-4aed-9094-4956f284d9c1", "historyId": "d6cede2ae4f2ad7eb3273b1681a85d44", "testCaseId": "f8334d9a8198a112d92f7233a3ae6f5e", "fullName": "tests.test_password_recoverty.TestsPasswordRecovery#test_enter_email_click_recovery", "labels": [{"name": "story", "value": "Тесты восстановления пароля"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_password_recoverty"}, {"name": "subSuite", "value": "TestsPasswordRecovery"}, {"name": "host", "value": "MBP-Oleg"}, {"name": "thread", "value": "84274-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_password_recoverty"}]}